export const photos = [
  { src: "/images/Gallery/IMG1.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG2.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG3.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG4.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG5.jpg", width: 3, height: 4 },
  { src: "/images/Gallery/IMG6.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG7.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG8.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG9.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG10.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG20.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG11.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG12.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG22.jpg", width: 3, height: 4 },
  { src: "/images/Gallery/IMG13.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG14.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG16.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG17.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG18.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG15.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG21.jpg", width: 3, height: 4 },
  { src: "/images/Gallery/IMG23.jpg", width: 4, height: 3 },
  { src: "/images/Gallery/IMG58.jpg", width: 3, height: 4 },  
  { src: "/images/Gallery/IMG70.jpg", width: 3, height: 4 },
  { src: "/images/Gallery/IMG83.jpg", width: 3, height: 4 },
  { src: "/images/Gallery/IMG111.jpg", width: 3, height: 4 },
];
