export const data = {
  chapterLead: [
    {
      id: 1,
      name: "Deepak Gupta",
      position: "Chairperson",
      img: "Deepak.webp",
      links: {
        link1: "https://www.linkedin.com/in/spycaptain/",
        link2: "https://github.com/spycaptain3",
        link3: "https://www.instagram.com/_spycaptain/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Deepak is a courageous and tenacious leader. He makes a great teammate. He serves as the Chairperson of the GeeksforGeeks SRMIST Delhi-NCR Chapter. Likewise, he is also a workhorse and always on time. Deepak is also a National Cadet Corps' Under Officer. He is actively practicing competitive programming and honing his talent in iOS app development.",
      },
      members: {},
      details: {},
    },
  ],

  leadList: [
    {
      id: 2,
      name: "Dhruv Pandey",
      position: "Vice Chairperson",
      img: "Dhruv.webp",
      links: {
        link1: "https://www.linkedin.com/in/dp2001",
        link2: "https://github.com/pandeydhruv2001",
        link3: "https://www.instagram.com/__the__neverending__footsteps_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Dhruv works well in a team and possesses a wide range of talents. Along with extensive technical expertise, he holds strong administrative and leadership abilities. He knows Python and Flutter and is proficient in C++ and MySQL. Currently, he is concentrating on honing his Data Structures Skills. He serves as the Vice Chairperson of the Delhi-NCR Chapter of GeeksforGeeks. In addition to this, he also serves as the ISTE SRMIST Chapter's Technical Head.",
      },
      members: {},
      details: {},
    },
    {
      id: 3,
      name: "Drish",
      position: "Technical Head",
      img: "Drish.webp",
      links: {
        link1: "https://www.linkedin.com/in/drish-xd/",
        link2: "https://github.com/Drish-xD",
        link3: "https://www.instagram.com/drish_xd/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.webp",
        slogan: "Minds that turn caffeine into code",
        desc: "The club's technological genius is Drish.He is an adept Web developer and is knowledgeable in the fundamentals of Full Stack Development. He is the GeeksforGeeks SRMIST Delhi-NCR Chapter's technical lead. Furthermore, he is the Core Member of the CodeChef SRMIST Chapter in addition to being the Technical Head of the GfG SRMIST Delhi-NCR Campus. He has been a contributor to GirlScript Winter of Contributing, Hacktoberfest 2021, and many such competitions. He is an enthusiastic professional who welcomes new experiences with open arms.",
      },
      members: {
        mem1: "Arshdeep Singh Virdi",
        mem2: "Rishi Rishabh",
        mem3: "Saksham Bhardwaj",
        mem4: "Sowmya Garg",
        mem5: "Hitesh Bajaj",
        mem6: "Swarnim Burnwal",
        mem7: "Ayush Mittal",
        mem8: "Harsh Gupta",
        mem9: "Naman Gururani",
        mem10: "Yatharth Gautam ",
        mem11: "Tanmay Newatia",
        mem12: "Tanish Khare",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "2nd year",
        det6: "2nd year",
        det7: "4th year",
        det8: "3rd year",
        det9: "4th year",
        det10: "3rd Year",
        det11: "3rd Year",
        det12: "4th Year",
      },
    },

    {
      id: 4,
      name: "Aditya Prabhakar",
      position: "Event Head",
      img: "Aditya.webp",
      links: {
        link1: "https://www.linkedin.com/in/aditya-prabhakar-b9a8a11a6",
        link2: "",
        link3: "",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.webp",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "Aditya is the GeeksforGeeks SRMIST Delhi-NCR Campus's Event Head. He is an accomplished speaker and has outstanding communication abilities. Furthermore, he is also proficient at programming, in addition to everything else. He is not just the GfG SRMIST Delhi-NCR Campus's event coordinator, he is also a member of the CSI SRM Chapter’s Video Design Team.",
      },
      members: {
        mem1: "Astha Vats",
        mem2: "Debasmita Mukherjee",
        mem3: "Aanya Singh",
        mem4: "Mayank Gangwar",
        mem5: "Anushka Sharma",
        mem6: "Vartika Bajpai",
        mem7: "Vanshika Rawat",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
      },
    },
    {
      id: 5,
      name: "Lahari Krishnam",
      position: "Marketing Head",
      img: "Lahari.webp",
      links: {
        link1: "https://www.linkedin.com/in/lahari03",
        link2: "",
        link3: "https://www.instagram.com/lahari_k03/",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.webp",
        slogan: "When the vision is flawless and the strategy is infallible.",
        desc: "Lahari is the GeeksforGeeks SRMIST Delhi-NCR Chapter's Marketing Head. She is the Content Head of the CSI SRMIST Chapter in addition to being the creative team member of MLSA SRM. She’s the upcoming Summer Intern at Barclay’s in 2023. Proficient in C, C++, Python and Front-End Development. She is a quick learner who can work effectively under pressure. She is constantly prepared to take on new problems and seek creative solutions. A committed individual with excellent communication and interpersonal abilities.",
      },
      members: {
        mem1: "Sanya Singh",
        mem2: "Shobhit Singh",
        mem3: "Shivam Singh",
        mem4: "Varun Saxena",
        mem5: "Karan Gupta",
        mem6: "Aviral Mittal",
        mem7: "Gautam Sharma",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "2nd year",
        det4: "2nd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
      },
    },
    {
      id: 6,
      name: "Srishti Dhingra",
      position: "Social Media Head",
      img: "Srishti.webp",
      links: {
        link1: "https://www.linkedin.com/in/srishti-dhingra-8797851b9",
        link2: "",
        link3: "https://www.instagram.com/srishti2631/",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.webp",
        slogan: "Sharing info that open opportunity for you",
        desc: "Srishti is a dedicated, meticulous, and ambitious student who excels in communication and multitasking. She is a 5-star coder in C++ and 4-star coder in C at HackerRank and is proficient in Python. She is the GeeksforGeeks SRMIST Delhi-NCR Chapter's Social Media Head.",
      },
      members: {
        mem1: "Sakshi Singh",
        mem2: "Arya Jha",
        mem3: "Priyanshi Tiwari",
        mem4: "Riya Dublish",
        mem5: "Sharad Choudhary",
        mem6: "Vaishnavi",
        mem7: "Divyanshi Sharma",
        mem8: "Akansha Jha",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "2nd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
        det8: "3rd year",
      },
    },
    {
      id: 7,
      name: "Pushpak Kumawat",
      position: "Design/Branding Head",
      img: "Pushpak.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "Designers",
        logo: "Designers.webp",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "Pushpak is the GeeksforGeeks SRMIST Delhi-NCR Chapter's Design/Branding Head. He is an ardent supporter of innovation and cutting-edge technology. He's an expert in C++. In addition, he has secured second position in the IDEATHON'22 and won the SHURU'21 organized by SRMIST.",
      },
      members: {
        mem1: "Arnav Sharma",
        mem2: "Raghav Nagpal",
        mem3: "Utkarsh Verma",
        mem4: "Mohak Kansal",
        mem5: "Yasir Mansoori",
        mem6: "Ekansh Srivastava",
        mem7: "Shrishti Maurya",
        mem8: "Harsh Dhiman",
        mem9: "Tushar Chauhan ",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "2nd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
        det8: "3rd year",
        det9: "3rd year",
      },
    },
    {
      id: 8,
      name: "Samriddha Basu",
      position: "P.R. Head",
      img: "Samriddha.webp",
      links: {
        link1: "http://www.linkedin.com/in/samriddha-basu-cloud",
        link2: "https://github.com/samriddha-basu-cloud",
        link3: "https://www.instagram.com/unsheathed.dmg/",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.webp",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "Samriddha is an ardent technophile and a cloud enthusiast. He speaks and presents well in front of an audience. He has a good command of C/C++ (5-star in HackerRank), and Java, and he’s working on Android Development using Kotlin. He also persists in finishing a work to perfection. Recently, he has successfully completed the requirements to be recognized as a Microsoft Certified: Azure Fundamentals practitioner. He's a quick learner and can adapt to changes quickly. He’s the PR Head at GfG SRM NCR Chapter. Likewise, he also serves as the CSI SRMIST Chapter's Technical Head.",
      },
      members: {
        mem1: "Sanya Vohra",
        mem2: "Arushee Kohli",
        mem3: "Paresh Bansal",
        mem4: "Shaurya Baijal",
        mem5: "Karan Raj Arya",
        mem6: "Kashish Behal",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
      },
    },
  ],
  facultyList: [
    // {
    //   id: 1,
    //   name: "Dr. Sanjay Viswanathan",
    //   position: "Director-SRM IST",
    //   img: "DR.webp",
    //   links: {},
    //   modal: {
    //     team: "Director-SRM IST",
    //     logo: "main.webp",
    //     slogan: "",
    //     desc: "Mr. Sanjay Vishwanathan has work as an Assistant manager from 1993- 1997 and as a Manager from 1997-2004 and as a Administrative officer from 2004 and currently he is the Director of Computer Science and Engineering at SRM-IST, Delhi NCR Campus Ghaziabad, India.He has pursued his M.B.A. from University of Madras. He joined SRM-IST in 1993. He has a managing experience of over 29 years at SRM-IST, NCR Campus, Modinagar.",
    //   },
    // },
    // {
    //   id: 2,
    //   name: "Dr. R.P. Mahapatra",
    //   position: "Prof. & HOD CSE / Dean Admission",
    //   img: "rp_mahapatra.webp",
    //   links: {},
    //   modal: {
    //     team: "Prof. & HOD CSE / Dean Admission",
    //     logo: "main.webp",
    //     slogan: "",
    //     desc: "Dr. R.P. Mahapatra is working as an Professor and Head of Department of Computer Science and Engineering and Dean Admission at SRM-IST, Delhi NCR Campus Ghaziabad, India.He has pursued his PhD from National Institute of Technology Mizoram. He joined SRM-IST in 2006. He has a teaching experience of over 16 years at SRM-IST, NCR Campus, Modinagar.",
    //   },
    // },
    {
      id: 3,
      name: "Mr. Naresh Sharma",
      position: "Assistant Professor Department of CSE",
      img: "Naresh.webp",
      links: {},
      modal: {
        team: "Club Convenor",
        logo: "main.webp",
        slogan: "",
        desc: "Mr. Naresh Sharma is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India. He is pursuing his PhD in Computer Science and Engineering. M. Tech. (Computer Science and Engineering) from Institute of Technology and Management, Gurgram, Maharshi Dayanand University, Rohtak, Haryana, India, and M.Sc. (Mathematics) in 2003 from Nanak Chand Anglo Sanskrit College, Chaudhary Charan Singh University, Meerut, Uttar Pradesh, India. He joined SRM-IST in 2009. He has a teaching experience of over 14 years at SRM-IST, NCR Campus, Modinagar, Ghaziabad, Uttar Pradesh, India. \n Mr. Sharma is an active member of ISTE, IE, and NDL. He is an editorial board member and Reviewer of more than 4 international journal and conferences. He has published about 15 research papers in Scopus, SCI, International/ National Journals and about 07 research papers in International/National Conferences. \nMr. Sharma is Reviewer of many International Journals / Conferences. Mr. Sharma has organised 7 International Conferences held in India. Mr. Sharma has participated in many International and National conferences as session Chair and Advisory or International Program Committees.",
      },
    },
    // {
    //   id: 4,
    //   name: "Nidhi Pandey",
    //   position: "Assistant Professor Department of CSE",
    //   img: "Nidhi.webp",
    //   links: {},
    //   modal: {
    //     team: "Faculty Coordinator",
    //     logo: "main.webp",
    //     slogan: "",
    //     desc: "Mrs.Nidhi Pandey is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India. She conducted the regular lectures for graduate students. Carried out practical sessions with explanation about the purpose of the experiment and procedures that follow to seek result. Assist in management and coordination of overall program, develop and adapt curriculum as necessary to achieve program objectives. Associate software engineer accenture 07/2015 - 10/2016, Pune, Maharashtra develop business architecture using requirements such as scope, processes, alternatives, and risks. analyze client’s business requirements and processes through document analysis. Conduct 5+ levels of testing including functional, regression, user acceptance, integration, and performance to verify the client’s needs are met. Identify and reconcile errors in client data to ensure accurate business requirements. Communicate client’s business requirements by constructing easy-to-understand data and process models. Engage client to gather software requirements/business rules, and ensure alignment with development teams. Draft and maintain business requirements and align them with functional and technical requirements. Paper publication & research.",
    //   },
    // },
    // {
    //   id: 5,
    //   name: "Bharti Vidhury",
    //   position: "Assistant Professor Department of CSE",
    //   img: "Bharti.webp",
    //   links: {},
    //   modal: {
    //     team: "Faculty Coordinator",
    //     logo: "main.webp",
    //     slogan: "",
    //     desc: "Ms.Bharti Vidhury is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India. She has pursued his M. Tech. (Computer Science and Engineering) in 2017 from Dr. A.P.J. Abdul Kalam Technical University (AKTU),Lucknow and B.Tech (Computer Science and Engineering) in 2015 from Dr. A.P.J. Abdul Kalam Technical University (AKTU),Lucknow. She joined SRM-IST in 2020. She has a teaching experience of over 5 years at SRM-IST, NCR Campus, Modinagar and other Institutions.",
    //   },
    // },
    // {
    //   id: 6,
    //   name: "Reena Grover",
    //   position: "Assistant Professor Department of CSE",
    //   img: "Reena_Grover.webp",
    //   links: {},
    //   modal: {
    //     team: "Support Faculty",
    //     logo: "main.webp",
    //     slogan: "",
    //     desc: "Mrs.Reena Grover is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India.She has pursued M.Sc.(Mathematics).She has pursued her PhD from Chaudhary Charan Singh University in 2013. She joined SRM-IST in 2015. She has a teaching experience of over 7 years at SRM-IST, NCR Campus, Modinagar.",
    //   },
    // },
  ],
};

// CURRENT TEAM LEADLIST

export const data1 = {
  chapterLead: [
    {
      id: 1,
      name: "Pushpak Kumawat",
      position: "Chairperson",
      img: "Pushpak.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "He is our President of the club Pushpak Kumawat, a computer science student at SRM University, specialising in machine learning and generative AI. His passion is using advanced technologies to create intelligent systems. He is currently pursuing my Bachelor's in Computer Science, focusing on machine learning, deep learning, and AI. He is skilled in implementing various ML algorithms, deep learning frameworks like TensorFlow and PyTorch, and generative AI techniques, including GANs and VAEs. He has worked on projects like image synthesis, text generation, and video prediction. He aspire to build a career at the intersection of machine learning and generative AI, pushing the boundaries of AI creativity.",
      },
      members: {},
      details: {},
    },
  ],

  leadList: [
    {
      id: 2,
      name: "Tanmay Newatia",
      position: "Vice Chairperson",
      img: "Tanmay.webp",
      links: {
        link1: "https://www.linkedin.com/in/tanmaynewatia/",
        link2: "https://www.github.com/TanmayNewatia",
        link3: "https://www.instagram.com/tanmay_newatia/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Tanmay works well in a team and possesses a wide range of talents. As a person, he is a Tech and Data enthusiast, along with a very keen interest in learning new things. He has built my web-development base with HTML, CSS, Javascript and Bootstrap. He is  leading towards learning ReactJS. Further, and have a good knowledge of programming languages such as Python, C++, and C. He serves as the Vice Chairperson of the Delhi-NCR Chapter of GeeksforGeeks.",
      },
      members: {},
      details: {},
    },
    {
      id: 3,
      name: "Arshdeep Singh",
      position: "Technical Head",
      img: "Arshdeep.webp",
      links: {
        link1: "https://www.linkedin.com/in/arshdeep-singh-virdi-a72a3a259/",
        link2: "https://github.com/ArshdeepSinghVirdi",
        link3: "https://www.instagram.com/__arsh__singh/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.webp",
        slogan: "Minds that turn caffeine into code",
        desc: "He is our technical genius Arshdeep Singh Virdi, an undergraduate student pursuing B. Tech in CSE at SRM University. He currently serves as Joint-Secretary of Student Council. As a person, he is a Tech and AI/ML enthusiast, along with a very keen interest in learning new things. He possess expertise in web development, complemented by prior knowledge in programming languages like Java, C++ and Dart. This background allows him to design and implement robust solutions for web-based projects.",
      },
      members: {
        mem1: "Swarnim Burnwal",
        mem2: "Aditya Kumar Singh",
        mem3: "Saksham Bhardwaj",
        mem4: "Hitesh Bajaj",
        mem5: "Rishi Rishab",
        mem6: "Devasheesh Mishra",
        mem7: "G.Nandini",
        mem8: "Debashish Behra",
        mem9: "",
        mem10: "",
        mem11: "",
        mem12: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "2nd year",
        det5: "2nd year",
        det6: "2nd year",
        det7: "1st year",
        det8: "1st year",
        det9: "",
        det10: "",
        det11: "",
        det12: "",
      },
    },

    {
      id: 4,
      name: "Kashish Behal",
      position: "Event Head",
      img: "Kashish.webp",
      links: {
        link1: "https://www.linkedin.com/in/kashish-behal-618100231/",
        link2: "https://github.com/KashishBehal",
        link3: "https://instagram.com/kashishbehal8?igshid=YmMyMTA2M2Y=",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.webp",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "She is our Event Handler Kashish Behal, a third-year computer science student with a passion for software development and research. She specialises in JavaScript and React.js, delving into both development and design aspects. She is proficient in programming languages like Python, C++, and C. She aims to combine creativity and technical expertise to create innovative solutions in the world of technology.",
      },
      members: {
        mem1: "Astha Vats",
        mem2: "Debasmita Mukherjee",
        mem3: "Aanya Singh",
        mem4: "Vartika Bajpai",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 5,
      name: "Shivam Singh",
      position: "Marketing Head",
      img: "Shivam.webp",
      links: {
        link1: " https://in.linkedin.com/in/shivam-singh-610390266",
        link2: " https://github.com/shivamsrm11",
        link3: "https://www.instagram.com/shi_vam_1122k2?igsh=NG95dW9iajM3ODM0",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.webp",
        slogan: "When the vision is flawless and the strategy is infallible.",
        desc: "He is our Marketing team lead Shivam Singh. He is current a third year student pursuing a bachleors degree in computer science. He is a curious Indiviual always looking way to market and spread news about all the events as quickly as possible. He has specialization in C/C++,python and also good in wed development . He has a keen interest in playing with data and experimenting with it .His excellent academic journey has also showed us was a true professional is like knowing how to balance academics as well as the working for the club.",
      },
      members: {
        mem1: "Gautam Sharma",
        mem2: "Akansha Jha",
        mem3: "Shivam Singh",
        mem4: "Shobhit Singh",
        mem5: "Tushar Chauhan",
        mem6: "Varun",
        mem7: "Sanya Singh",
      },
      details: {
        det1: "3rd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
      },
    },
    {
      id: 6,
      name: "Srishti Srivastava",
      position: "Social Media Head",
      img: "Srishti.webp",
      links: {
        link1: " https://www.linkedin.com/in/srishtii27/",
        link2: "https://github.com/Srishtii-27",
        link3: " https://instagram.com/srishtii.27?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.webp",
        slogan: "Sharing info that open opportunity for you",
        desc: "She is our Social media team lead Srishti Srivastava.She is currently pursuing BTech in computer science and engineering. She is a fast and keen learner with a strong foundation in programming languages like C++, and C. Her knowledge extends to Object Oriented Programming,  basic DSA and python. She is also paving my way into Development. She is eager to continue expanding my skills and knowledge to contribute to the world of technology.",
      },
      members: {
        mem1: "Sakshi Sharma",
        mem2: "Riya Dublish",
        mem3: "Priyanshi Tiwari",
        mem4: "Sowmya Garg",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 7,
      name: "Harsh Dhiman",
      position: "Design/Branding Head",
      img: "Harsh.webp",
      links: {
        link1: "https://www.linkedin.com/in/harsh-dhiman-2a111422b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/harshdhiman03",
        link3: "https://instagram.com/harsh.dhimann?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Designers",
        logo: "Designers.webp",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "He is our creative team lead, Harsh Diman. With extensive expertise in Adobe Photoshop and Illustrator, I've crafted captivating designs that have made a mark in various settings. He was also involved as a representative for my college at Thomso'22, IIT Roorkee, reflects his dedication to design. He has designed logos for all departments within GFG SRMIST DELHI NCR CAMPUS Student Chapter, showcasing his commitment to visual excellence and creativity.He is proficient in programming languages such as C++ and Python, adding a versatile dimension to his creative abilities.",
      },
      members: {
        mem1: "Mohak Kansal",
        mem2: "Adarsh Rai",
        mem3: "Raghav Nagpal",
        mem4: "Utkarsh Verma",
        mem5: "Amit Kumar",
        mem6: "Arnav Sharma",
        mem7: "",
        mem8: "",
        mem9: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "",
        det8: "",
        det9: "",
      },
    },
    {
      id: 8,
      name: "Shobhit Singh",
      position: "P.R. Head",
      img: "Shobhit.webp",
      links: {
        link1: "https://www.linkedin.com/in/shobhitsgh?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/shobhitdevelops",
        link3: "https://www.instagram.com/_shobhitsingh?igsh=MXViamEwOTFiemU2MA==",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.webp",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "The club’s public relations Team lead Shobhit, is a passionate college student at SRM University pursuing a B. Tech in Computer Science and Engineering. Dedicated to exploring the cutting-edge realms of computer science, I thrive on challenges and problem-solving. Adept at coding, and software development, and eager to contribute innovative solutions to the tech landscape. Committed to continuous learning and staying abreast of the latest advancements, and aspire to make meaningful contributions to the ever-evolving field of technology.",
      },
      members: {
        mem1: "Sanya Vohra",
        mem2: "Arushee Kohli",
        mem3: "Vaishnavi",
        mem4: "",
        mem5: "",
        mem6: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "",
        det5: "",
        det6: "",
      },
    },
  ],
};


export const data2 = {
  chapterLead: [
    {
      id: 1,
      name: "Arshdeep Singh Virdi",
      position: "Chairperson",
      img: "Arshdeep.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "He is our President of the club Pushpak Kumawat, a computer science student at SRM University, specialising in machine learning and generative AI. His passion is using advanced technologies to create intelligent systems. He is currently pursuing my Bachelor's in Computer Science, focusing on machine learning, deep learning, and AI. He is skilled in implementing various ML algorithms, deep learning frameworks like TensorFlow and PyTorch, and generative AI techniques, including GANs and VAEs. He has worked on projects like image synthesis, text generation, and video prediction. He aspire to build a career at the intersection of machine learning and generative AI, pushing the boundaries of AI creativity.",
      },
      members: {},
      details: {},
    },
  ],

  leadList: [
    {
      id: 2,
      name: "Aastha Vats",
      position: "Vice Chairperson",
      img: "Aastha.webp",
      links: {
        link1: "https://www.linkedin.com/in/tanmaynewatia/",
        link2: "https://www.github.com/TanmayNewatia",
        link3: "https://www.instagram.com/tanmay_newatia/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Tanmay works well in a team and possesses a wide range of talents. As a person, he is a Tech and Data enthusiast, along with a very keen interest in learning new things. He has built my web-development base with HTML, CSS, Javascript and Bootstrap. He is  leading towards learning ReactJS. Further, and have a good knowledge of programming languages such as Python, C++, and C. He serves as the Vice Chairperson of the Delhi-NCR Chapter of GeeksforGeeks.",
      },
      members: {},
      details: {},
    },
    {
      id: 3,
      name: "Swarnim Burnwal",
      position: "Technical Head",
      img: "Swarnim.webp",
      links: {
        link1: "https://www.linkedin.com/in/arshdeep-singh-virdi-a72a3a259/",
        link2: "https://github.com/ArshdeepSinghVirdi",
        link3: "https://www.instagram.com/__arsh__singh/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.webp",
        slogan: "Minds that turn caffeine into code",
        desc: "He is our technical genius Swarnim Burnwal, an undergraduate student pursuing B. Tech in CSE at SRM University. He currently serves as Joint-Secretary of Student Council. As a person, he is a Tech and AI/ML enthusiast, along with a very keen interest in learning new things. He possess expertise in web development, complemented by prior knowledge in programming languages like Java, C++ and Dart. This background allows him to design and implement robust solutions for web-based projects.",
      },
      members: {
        mem1: "Debashish Behra",
        mem2: "Aditya Kumar Singh",
        mem3: "Saksham Bhardwaj",
        mem4: "Hitesh Bajaj",
        mem5: "Rishi Rishab",
        mem6: "Devasheesh Mishra",
        mem7: "",
        mem8: "",
        mem9: "",
        mem10: "",
        mem11: "",
        mem12: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "2nd year",
        det5: "2nd year",
        det6: "2nd year",
        det7: "1st year",
        det8: "1st year",
        det9: "",
        det10: "",
        det11: "",
        det12: "",
      },
    },

    {
      id: 4,
      name: "Debasmitha Mukherjee",
      position: "Event Head",
      img: "Debasmita.webp",
      links: {
        link1: "https://www.linkedin.com/in/kashish-behal-618100231/",
        link2: "https://github.com/KashishBehal",
        link3: "https://instagram.com/kashishbehal8?igshid=YmMyMTA2M2Y=",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.webp",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "She is our Event Handler Kashish Behal, a third-year computer science student with a passion for software development and research. She specialises in JavaScript and React.js, delving into both development and design aspects. She is proficient in programming languages like Python, C++, and C. She aims to combine creativity and technical expertise to create innovative solutions in the world of technology.",
      },
      members: {
        mem1: "Astha Vats",
        mem2: "Debasmita Mukherjee",
        mem3: "Aanya Singh",
        mem4: "Vartika Bajpai",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 5,
      name: "Lakshay",
      position: "Marketing Head",
      img: "Lakshay.webp",
      links: {
        link1: " https://in.linkedin.com/in/shivam-singh-610390266",
        link2: " https://github.com/shivamsrm11",
        link3: "https://www.instagram.com/shi_vam_1122k2?igsh=NG95dW9iajM3ODM0",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.webp",
        slogan: "When the vision is flawless and the strategy is infallible.",
        desc: "He is our Marketing team lead Shivam Singh. He is current a third year student pursuing a bachleors degree in computer science. He is a curious Indiviual always looking way to market and spread news about all the events as quickly as possible. He has specialization in C/C++,python and also good in wed development . He has a keen interest in playing with data and experimenting with it .His excellent academic journey has also showed us was a true professional is like knowing how to balance academics as well as the working for the club.",
      },
      members: {
        mem1: "Gautam Sharma",
        mem2: "Akansha Jha",
        mem3: "Shivam Singh",
        mem4: "Shobhit Singh",
        mem5: "Tushar Chauhan",
        mem6: "Varun",
        mem7: "Sanya Singh",
      },
      details: {
        det1: "3rd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
      },
    },
    {
      id: 6,
      name: "Anshita Mishra",
      position: "Social Media Head",
      img: "Anshita.webp",
      links: {
        link1: " https://www.linkedin.com/in/srishtii27/",
        link2: "https://github.com/Srishtii-27",
        link3: " https://instagram.com/srishtii.27?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.webp",
        slogan: "Sharing info that open opportunity for you",
        desc: "She is our Social media team lead Srishti Srivastava.She is currently pursuing BTech in computer science and engineering. She is a fast and keen learner with a strong foundation in programming languages like C++, and C. Her knowledge extends to Object Oriented Programming,  basic DSA and python. She is also paving my way into Development. She is eager to continue expanding my skills and knowledge to contribute to the world of technology.",
      },
      members: {
        mem1: "Sakshi Sharma",
        mem2: "Riya Dublish",
        mem3: "Priyanshi Tiwari",
        mem4: "Sowmya Garg",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 7,
      name: "Shresth",
      position: "Design/Branding Head",
      img: "Shresth.webp",
      links: {
        link1: "https://www.linkedin.com/in/harsh-dhiman-2a111422b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/harshdhiman03",
        link3: "https://instagram.com/harsh.dhimann?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Designers",
        logo: "Designers.webp",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "He is our creative team lead, Harsh Diman. With extensive expertise in Adobe Photoshop and Illustrator, I've crafted captivating designs that have made a mark in various settings. He was also involved as a representative for my college at Thomso'22, IIT Roorkee, reflects his dedication to design. He has designed logos for all departments within GFG SRMIST DELHI NCR CAMPUS Student Chapter, showcasing his commitment to visual excellence and creativity.He is proficient in programming languages such as C++ and Python, adding a versatile dimension to his creative abilities.",
      },
      members: {
        mem1: "Mohak Kansal",
        mem2: "Adarsh Rai",
        mem3: "Raghav Nagpal",
        mem4: "Utkarsh Verma",
        mem5: "Amit Kumar",
        mem6: "Arnav Sharma",
        mem7: "",
        mem8: "",
        mem9: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "",
        det8: "",
        det9: "",
      },
    },
    {
      id: 8,
      name: "Archit",
      position: "P.R. Head",
      img: "Archit.webp",
      links: {
        link1: "https://www.linkedin.com/in/shobhitsgh?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/shobhitdevelops",
        link3: "https://www.instagram.com/_shobhitsingh?igsh=MXViamEwOTFiemU2MA==",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.webp",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "The club’s public relations Team lead Shobhit, is a passionate college student at SRM University pursuing a B. Tech in Computer Science and Engineering. Dedicated to exploring the cutting-edge realms of computer science, I thrive on challenges and problem-solving. Adept at coding, and software development, and eager to contribute innovative solutions to the tech landscape. Committed to continuous learning and staying abreast of the latest advancements, and aspire to make meaningful contributions to the ever-evolving field of technology.",
      },
      members: {
        mem1: "Sanya Vohra",
        mem2: "Arushee Kohli",
        mem3: "Vaishnavi",
        mem4: "",
        mem5: "",
        mem6: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "",
        det5: "",
        det6: "",
      },
    },
  ],
};
