export const data = {
  leadList: [
    {
      id: 1,
      name: "Deepak Gupta",
      position: "Chairperson",
      img: "Deepak.webp",
      links: {
        link1: "https://www.linkedin.com/in/spycaptain/",
        link2: "https://github.com/spycaptain3",
        link3: "https://www.instagram.com/_spycaptain/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.jpeg",
        slogan: "",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 2,
      name: "Dhruv Pandey",
      position: "Vice Chairperson",
      img: "Dhruv.webp",
      links: {
        link1: "https://www.linkedin.com/in/dp2001",
        link2: "https://github.com/pandeydhruv2001",
        link3: "https://www.instagram.com/__the__neverending__footsteps_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.jpeg",
        slogan: "",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 3,
      name: "Drish",
      position: "Technical Head",
      img: "Drish.webp",
      links: {
        link1: "https://www.linkedin.com/in/drish-xd/",
        link2: "https://github.com/Drish-xD",
        link3: "https://www.instagram.com/drish_xd/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.png",
        slogan: "Minds that turn caffeine into code",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 4,
      name: "Aditya Prabhakar",
      position: "Event Head",
      img: "Aditya.webp",
      links: {
        link1: "https://www.linkedin.com/in/aditya-prabhakar-b9a8a11a6",
        link2: "",
        link3: "",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.png",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 5,
      name: "Lahari Krishnam",
      position: "Marketing Head",
      img: "Lahari.webp",
      links: {
        link1: "https://www.linkedin.com/in/lahari03",
        link2: "",
        link3: "https://www.instagram.com/lahari_k03/",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.png",
        slogan: "When the vision is flawless and the strategy is infallible.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 6,
      name: "Srishti Dhingra",
      position: "Social Media Head",
      img: "Srishti.webp",
      links: {
        link1: "https://www.linkedin.com/in/srishti-dhingra-8797851b9",
        link2: "",
        link3: "https://www.instagram.com/srishti2631/",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.png",
        slogan: "Sharing info that open opportunity for you",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 7,
      name: "Pushpak Kumawat",
      position: "Design/Branding Head",
      img: "Pushpak.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "Designers",
        logo: "Designers.png",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 8,
      name: "Samriddha Basu",
      position: "P.R. Head",
      img: "Samriddha.webp",
      links: {
        link1: "http://www.linkedin.com/in/samriddha-basu-cloud",
        link2: "https://github.com/samriddha-basu-cloud",
        link3: "https://www.instagram.com/unsheathed.dmg/",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.png",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
  ],
  facultyList: [
    {
      id: 1,
      name: "Dr. Sanjay Viswanathan",
      position: "",
      img: "team.webp",
      links: {},
      modal: {
        team: "Director-SRM IST",
        logo: "main.jpeg",
        slogan: "",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 2,
      name: "Dr. R.P. Mahapatra",
      position: "",
      img: "team.webp",
      links: {},
      modal: {
        team: "Dean Admission",
        logo: "main.jpeg",
        slogan: "",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 3,
      name: "Mr. Naresh Sharma",
      position: "",
      img: "team.webp",
      links: {},
      modal: {
        team: "Club Convenors",
        logo: "main.jpeg",
        slogan: "",
        desc: "Mr. Naresh Sharma is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India. He is pursuing his PhD in Computer Science and Engineering. He has pursued his M. Tech. (Computer Science and Engineering) from Institute of Technology and Management, Gurgram, Maharshi Dayanand University, Rohtak and M.Sc. (Mathematics) in 2003 from Nanak Chand Anglo Sanskrit College, Chaudhary Charan Singh University, Meerut. He joined SRM-IST in 2009. He has a teaching experience of over 14 years at SRM-IST, NCR Campus, Modinagar.",
      },
    },
    {
      id: 4,
      name: "Nidhi Pandey",
      position: "Assistant Professor Department of CSE",
      img: "team.webp",
      links: {},
      modal: {
        team: "Faculty Coordinator",
        logo: "main.jpeg",
        slogan: "",
        desc: "Mrs.Nidhi Pandey is working as an Assistant Professor of Computer Science and Engineering, SRM-IST, Delhi NCR Campus Ghaziabad, India. She conducted the regular lectures for graduate students. Carried out practical sessions with explanation about the purpose of the experiment and procedures that follow to seek result. Assist in management and coordination of overall program, develop and adapt curriculum as necessary to achieve program objectives. Associate software engineer accenture 07/2015 - 10/2016, Pune, Maharashtra develop business architecture using requirements such as scope, processes, alternatives, and risks. analyze client’s business requirements and processes through document analysis. Conduct 5+ levels of testing including functional, regression, user acceptance, integration, and performance to verify the client’s needs are met. Identify and reconcile errors in client data to ensure accurate business requirements. Communicate client’s business requirements by constructing easy-to-understand data and process models. Engage client to gather software requirements/business rules, and ensure alignment with development teams. Draft and maintain business requirements and align them with functional and technical requirements. Paper publication & research.",
      },
    },
    {
      id: 5,
      name: "Bharti Vidhury",
      position: "Assistant Professor Department of CSE",
      img: "Bharti.webp",
      links: {},
      modal: {
        team: "Faculty Coordinator",
        logo: "main.jpeg",
        slogan: "",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
  ],
};
