export const data = {
  leadList: [
    {
      id: 1,
      name: "Deepak Gupta",
      position: "Chairperson",
      img: "Deepak.webp",
      links: {
        link1: "https://www.linkedin.com/in/spycaptain/",
        link2: "https://github.com/spycaptain3",
        link3: "https://www.instagram.com/_spycaptain/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.jpeg",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 2,
      name: "Dhruv Pandey",
      position: "Vice Chairperson",
      img: "Dhruv.webp",
      links: {
        link1: "https://www.linkedin.com/in/dp2001",
        link2: "https://github.com/pandeydhruv2001",
        link3: "https://www.instagram.com/__the__neverending__footsteps_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.jpeg",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 3,
      name: "Drish",
      position: "Technical Head",
      img: "Drish.webp",
      links: {
        link1: "https://www.linkedin.com/in/drish-xd/",
        link2: "https://github.com/Drish-xD",
        link3: "https://www.instagram.com/drish_xd/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 4,
      name: "Aditya Prabhakar",
      position: "Event Head",
      img: "Aditya.webp",
      links: {
        link1: "https://www.linkedin.com/in/aditya-prabhakar-b9a8a11a6",
        link2: "",
        link3: "",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 5,
      name: "Lahari Krishnam",
      position: "Marketing Head",
      img: "Lahari.webp",
      links: {
        link1: "https://www.linkedin.com/in/lahari03",
        link2: "",
        link3: "https://www.instagram.com/lahari_k03/",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 6,
      name: "Srishti Dhingra",
      position: "Social Media Head",
      img: "Srishti.webp",
      links: {
        link1: "https://www.linkedin.com/in/srishti-dhingra-8797851b9",
        link2: "",
        link3: "https://www.instagram.com/srishti2631/",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 7,
      name: "Pushpak Kumawat",
      position: "Design/Branding Head",
      img: "Pushpak.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "Designers",
        logo: "Designers.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
    {
      id: 8,
      name: "Samriddha Basu",
      position: "P.R. Head",
      img: "Samriddha.webp",
      links: {
        link1: "http://www.linkedin.com/in/samriddha-basu-cloud",
        link2: "https://github.com/samriddha-basu-cloud",
        link3: "https://www.instagram.com/unsheathed.dmg/",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
  ],
  facultyList: [
    {
      id: 1,
      name: "Bharti Vidhury",
      position: "Assistant Professor Department of CSE",
      img: "Faculty.webp",
      links: {},
      modal: {
        team: "GFG",
        logo: "PR.png",
        slogan: "Lorem ipsum dolor sit amet.",
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nobis dolor incidunt eius doloremque provident accusamus non. Doloremque, architecto id sint quisquam autem perspiciatis fugiat dolore quidem natus nulla! Quis quod, atque eum sint ea molestias explicabo a voluptatum maxime corrupti sapiente ut illo asperiores, odio temporibus repellendus quam. Debitis mollitia voluptates voluptas iusto laudantium minus veritatis dolores non aliquam. Nam temporibus, nisi assumenda cupiditate labore voluptate, possimus ab nostrum molestias eius quo rem explicabo officiis, repudiandae perferendis recusandae tempora ex eos maiores inventore. Explicabo facere dolore nemo rem, nobis ipsa praesentium deserunt asperiores qui non autem doloribus obcaecati neque!",
      },
    },
  ],
};
