// OLD TEAM LEADLIST

export const previousMembers = {
  chapterLead: [
    {
      id: 1,
      name: "Pushpak Kumawat",
      position: "Chairperson",
      img: "Pushpak.webp",
      links: {
        link1: "https://www.linkedin.com/in/pushpak-kumawat-b4bb921ba/",
        link2: "https://github.com/1pushpak1",
        link3: "https://www.instagram.com/_pushpak_k_/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "He is our President of the club Pushpak Kumawat, a computer science student at SRM University, specialising in machine learning and generative AI. His passion is using advanced technologies to create intelligent systems. He is currently pursuing my Bachelor's in Computer Science, focusing on machine learning, deep learning, and AI. He is skilled in implementing various ML algorithms, deep learning frameworks like TensorFlow and PyTorch, and generative AI techniques, including GANs and VAEs. He has worked on projects like image synthesis, text generation, and video prediction. He aspire to build a career at the intersection of machine learning and generative AI, pushing the boundaries of AI creativity.",
      },
      members: {},
      details: {},
    },
  ],

  leadList: [
    {
      id: 2,
      name: "Tanmay Newatia",
      position: "Vice Chairperson",
      img: "Tanmay.webp",
      links: {
        link1: "https://www.linkedin.com/in/tanmaynewatia/",
        link2: "https://www.github.com/TanmayNewatia",
        link3: "https://www.instagram.com/tanmay_newatia/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Tanmay works well in a team and possesses a wide range of talents. As a person, he is a Tech and Data enthusiast, along with a very keen interest in learning new things. He has built my web-development base with HTML, CSS, Javascript and Bootstrap. He is  leading towards learning ReactJS. Further, and have a good knowledge of programming languages such as Python, C++, and C. He serves as the Vice Chairperson of the Delhi-NCR Chapter of GeeksforGeeks.",
      },
      members: {},
      details: {},
    },
    {
      id: 3,
      name: "Arshdeep Singh",
      position: "Technical Head",
      img: "Arshdeep.webp",
      links: {
        link1: "https://www.linkedin.com/in/arshdeep-singh-virdi-a72a3a259/",
        link2: "https://github.com/ArshdeepSinghVirdi",
        link3: "https://www.instagram.com/__arsh__singh/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.webp",
        slogan: "Minds that turn caffeine into code",
        desc: "He is our technical genius Arshdeep Singh Virdi, an undergraduate student pursuing B. Tech in CSE at SRM University. He currently serves as Joint-Secretary of Student Council. As a person, he is a Tech and AI/ML enthusiast, along with a very keen interest in learning new things. He possess expertise in web development, complemented by prior knowledge in programming languages like Java, C++ and Dart. This background allows him to design and implement robust solutions for web-based projects.",
      },
      members: {
        mem1: "Swarnim Burnwal",
        mem2: "Aditya Kumar Singh",
        mem3: "Saksham Bhardwaj",
        mem4: "Hitesh Bajaj",
        mem5: "Rishi Rishab",
        mem6: "Devasheesh Mishra",
        mem7: "G.Nandini",
        mem8: "Debashish Behra",
        mem9: "",
        mem10: "",
        mem11: "",
        mem12: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "2nd year",
        det5: "2nd year",
        det6: "2nd year",
        det7: "1st year",
        det8: "1st year",
        det9: "",
        det10: "",
        det11: "",
        det12: "",
      },
    },

    {
      id: 4,
      name: "Kashish Behal",
      position: "Event Head",
      img: "Kashish.webp",
      links: {
        link1: "https://www.linkedin.com/in/kashish-behal-618100231/",
        link2: "https://github.com/KashishBehal",
        link3: "https://instagram.com/kashishbehal8?igshid=YmMyMTA2M2Y=",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.webp",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "She is our Event Handler Kashish Behal, a third-year computer science student with a passion for software development and research. She specialises in JavaScript and React.js, delving into both development and design aspects. She is proficient in programming languages like Python, C++, and C. She aims to combine creativity and technical expertise to create innovative solutions in the world of technology.",
      },
      members: {
        mem1: "Astha Vats",
        mem2: "Debasmita Mukherjee",
        mem3: "Aanya Singh",
        mem4: "Vartika Bajpai",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 5,
      name: "Shivam Singh",
      position: "Marketing Head",
      img: "Shivam.webp",
      links: {
        link1: " https://in.linkedin.com/in/shivam-singh-610390266",
        link2: " https://github.com/shivamsrm11",
        link3: "https://www.instagram.com/shi_vam_1122k2?igsh=NG95dW9iajM3ODM0",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.webp",
        slogan: "When the vision is flawless and the strategy is infallible.",
        desc: "He is our Marketing team lead Shivam Singh. He is current a third year student pursuing a bachleors degree in computer science. He is a curious Indiviual always looking way to market and spread news about all the events as quickly as possible. He has specialization in C/C++,python and also good in wed development . He has a keen interest in playing with data and experimenting with it .His excellent academic journey has also showed us was a true professional is like knowing how to balance academics as well as the working for the club.",
      },
      members: {
        mem1: "Gautam Sharma",
        mem2: "Akansha Jha",
        mem3: "Shivam Singh",
        mem4: "Shobhit Singh",
        mem5: "Tushar Chauhan",
        mem6: "Varun",
        mem7: "Sanya Singh",
      },
      details: {
        det1: "3rd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
      },
    },
    {
      id: 6,
      name: "Srishti Srivastava",
      position: "Social Media Head",
      img: "Srishti.webp",
      links: {
        link1: " https://www.linkedin.com/in/srishtii27/",
        link2: "https://github.com/Srishtii-27",
        link3: " https://instagram.com/srishtii.27?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.webp",
        slogan: "Sharing info that open opportunity for you",
        desc: "She is our Social media team lead Srishti Srivastava.She is currently pursuing BTech in computer science and engineering. She is a fast and keen learner with a strong foundation in programming languages like C++, and C. Her knowledge extends to Object Oriented Programming,  basic DSA and python. She is also paving my way into Development. She is eager to continue expanding my skills and knowledge to contribute to the world of technology.",
      },
      members: {
        mem1: "Sakshi Sharma",
        mem2: "Riya Dublish",
        mem3: "Priyanshi Tiwari",
        mem4: "Sowmya Garg",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 7,
      name: "Harsh Dhiman",
      position: "Design/Branding Head",
      img: "Harsh.webp",
      links: {
        link1:
          "https://www.linkedin.com/in/harsh-dhiman-2a111422b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/harshdhiman03",
        link3: "https://instagram.com/harsh.dhimann?igshid=MzMyNGUyNmU2YQ==",
      },
      modal: {
        team: "Designers",
        logo: "Designers.webp",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "He is our creative team lead, Harsh Diman. With extensive expertise in Adobe Photoshop and Illustrator, I've crafted captivating designs that have made a mark in various settings. He was also involved as a representative for my college at Thomso'22, IIT Roorkee, reflects his dedication to design. He has designed logos for all departments within GFG SRMIST DELHI NCR CAMPUS Student Chapter, showcasing his commitment to visual excellence and creativity.He is proficient in programming languages such as C++ and Python, adding a versatile dimension to his creative abilities.",
      },
      members: {
        mem1: "Mohak Kansal",
        mem2: "Adarsh Rai",
        mem3: "Raghav Nagpal",
        mem4: "Utkarsh Verma",
        mem5: "Amit Kumar",
        mem6: "Arnav Sharma",
        mem7: "",
        mem8: "",
        mem9: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "",
        det8: "",
        det9: "",
      },
    },
    {
      id: 8,
      name: "Shobhit Singh",
      position: "P.R. Head",
      img: "Shobhit.webp",
      links: {
        link1:
          "https://www.linkedin.com/in/shobhitsgh?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/shobhitdevelops",
        link3:
          "https://www.instagram.com/_shobhitsingh?igsh=MXViamEwOTFiemU2MA==",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.webp",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "The club’s public relations Team lead Shobhit, is a passionate college student at SRM University pursuing a B. Tech in Computer Science and Engineering. Dedicated to exploring the cutting-edge realms of computer science, I thrive on challenges and problem-solving. Adept at coding, and software development, and eager to contribute innovative solutions to the tech landscape. Committed to continuous learning and staying abreast of the latest advancements, and aspire to make meaningful contributions to the ever-evolving field of technology.",
      },
      members: {
        mem1: "Sanya Vohra",
        mem2: "Arushee Kohli",
        mem3: "Vaishnavi",
        mem4: "",
        mem5: "",
        mem6: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "",
        det5: "",
        det6: "",
      },
    },
  ],
};

// NEW TEAM LEADLIST
export const currentMembers = {
  chapterLead: [
    {
      id: 1,
      name: "Arshdeep Singh Virdi",
      position: "Chairperson",
      img: "Arshdeep.webp",
      links: {
        link1: "https://www.linkedin.com/in/arshdeep-singh-virdi-a72a3a259/",
        link2: "https://github.com/ArshdeepSinghVirdi",
        link3: "https://www.instagram.com/__arsh__singh/",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "He is our technical genius Arshdeep Singh Virdi, an undergraduate student pursuing B. Tech in CSE at SRM University. He currently serves as Joint-Secretary of Student Council. As a person, he is a Tech and AI/ML enthusiast, along with a very keen interest in learning new things. He possess expertise in web development, complemented by prior knowledge in programming languages like Java, C++ and Dart. This background allows him to design and implement robust solutions for web-based projects.",
      },
      members: {},
      details: {},
    },
  ],

  leadList: [
    {
      id: 2,
      name: "Aastha Vats",
      position: "Vice Chairperson",
      img: "Aastha.webp",
      links: {
        link1: "https://www.linkedin.com/in/aastha-vats-b12893276",
        link2: "https://github.com/aasthavats16",
        link3: "https://www.instagram.com/aasthavats16 ",
      },
      modal: {
        team: "GFG Chapter",
        logo: "main.webp",
        slogan: "",
        desc: "Aastha Vats is a distinguished leader with a robust background in Data Science, excelling in Machine Learning, Python, SQL, and TensorFlow. Her technical expertise is complemented by exceptional communication and public speaking skills, allowing her to convey complex concepts with precision and confidence. Aastha’s unwavering commitment to academic excellence and continuous learning has propelled her to the role of Vice Chairperson for the GeeksforGeeks SRMIST Delhi-NCR Student Chapter, where she adeptly inspires and guides her peers with both her technical acumen and visionary leadership.",
      },
      members: {},
      details: {},
    },
    {
      id: 3,
      name: "Swarnim Burnwal",
      position: "Technical Head",
      img: "Swarnim.webp",
      links: {
        link1: "https://www.linkedin.com/in/swarnim-burnwal-616720249/",
        link2: "https://github.com/SWARNIM-BURNWAL",
        link3: "https://www.instagram.com/_swarnim.burnwal_/",
      },
      modal: {
        team: "Tech Minds",
        logo: "Tech.webp",
        slogan: "Minds that turn caffeine into code",
        desc: "Swarnim Burnwal is a driven leader with a strong foundation in programming, robotics, and machine learning. Proficient in Python, C, C++, JavaScript, and frameworks like ReactJS and NextJS, Swarnim combines technical expertise with a deep understanding of data structures, algorithms, and neural networks. His hands-on experience with tools like Docker, Git, and GitHub, alongside proficiency in MySQL, MongoDB, and Linux, showcases his versatile skill set. As an expert in both hardware and software, Swarnim excels in robotics projects using Arduino, Raspberry Pi, and ArduPilot. His passion for continuous learning and innovation is evident in his contributions to various technical projects and his leadership as the Technical Lead for the GeeksforGeeks SRMIST Delhi-NCR Student Chapter. Swarnim’s commitment to excellence and ability to inspire peers make him a valuable asset in the tech community.",
      },
      members: {
        mem1: "Debashish Behra",
        mem2: "Hitesh Bajaj",
        mem3: "Ritika Sharma",
        mem4: "Arpit Singhal",
        mem5: "Manasvi Srivastava",
        mem6: "Devasheesh Mishra",
        mem7: "Ayush Gupta",
        mem8: "Aaryan Singh Tomar",
        mem9: "Arpit Singhal",
        mem10: "Hitakshi",
        mem11: "Krishant Basotra",
        mem12: "Sandeli Tiwari",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "3rd year",
        det7: "3rd year",
        det8: "2nd year",
        det9: "3rd year",
        det10: "2nd year",
        det11: "2nd year",
        det12: "2nd year",
      },
    },

   {
      id: 4,
      name: "Vaibhav Sharma",
      position: "Event Head",
      img: "vaibhavevent.png",
      links: {
        link1: "https://x.com/Imvaibhavsha?t=ybW2N0jk5aqZNb6ByEQGMg&s=09",
        link2: " https://github.com/Deadshot4478 ",
        link3: "https://www.instagram.com/vaibhav_sharma_447?igsh=YWszbGNqengxemZp",
      },
      modal: {
        team: "Event Enthusiastic",
        logo: "Event.webp",
        slogan:
          "Other people look for a beautiful place. While the planners make a place beautiful.",
        desc: "Vaibhav Sharma, a second-year Core B.Tech student at SRMIST Delhi-NCR, is a passionate event organizer and leader. Fluent in C++, his go-to tech stack includes MongoDB, React, JavaScript, and EJS. Since joining SRMIST, he has played a crucial role in organizing several prestigious events, such as Innovate 2024, Anadotsav 2025, Engineer's Week, Ganesh Utsav, Swagatham 2025, the 28th Foundation Day, the Alumni Meet 2025, Projectoria, and various Geeks for Geeks workshops.With a strong drive for leadership and innovation, Vaibhav strives to create engaging and memorable events. His vision is to enhance his leadership skills and push the boundaries of event planning, ensuring each event is bigger and better than the last.",
      },
      members: {
        mem1: "Aryan Tiwari",
        mem2: "Aali Sahay",
        mem3: "Anobhav Singh ",
        mem4: "",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 5,
      name: "Lakshya Arora",
      position: "Marketing Head",
      img: "Lakshay.webp",
      links: {
        link1: " https://www.linkedin.com/in/lakshya-arora-76a567259/",
        link2: "https://github.com/Lakshya300104",
        link3: "https://www.instagram.com/lakshyyaarora/",
      },
      modal: {
        team: "Marketing Wizards",
        logo: "Marketing.webp",
        slogan:
          "Lakshya Arora is a dynamic Marketing Lead and a dedicated third-year Computer Science student with a specialization in Python and Data Science. Lakshya brings a robust technical skill set to their role. He excel at leveraging these skills to craft data-driven marketing strategies and insights. Beyond their technical prowess, he is an accomplished public speaker, investing significantly in their oratory skills to effectively combine technology and communication. This unique blend of technical expertise and eloquent presentation allows him to bridge the gap between complex technological concepts and engaging public discourse.",
      },
      members: {
        mem1: "Anushka Jain",
        mem2: "Tanuj Kochar ",
        mem3: "",
        mem4: "",
        mem5: "",
        mem6: "",
        mem7: "",
      },
      details: {
        det1: "3rd year",
        det2: "2nd year",
        det3: "",
        det4: "",
        det5: "",
        det6: "",
        det7: "",
      },
    },
    {
      id: 6,
      name: "Anshita Mishra",
      position: "Social Media Head",
      img: "Anshita.webp",
      links: {
        link1: " https://www.linkedin.com/in/anshita-mishra-0b798a2a4",
        link2: "https://github.com/anshitamishra ",
        link3: "  https://www.instagram.com/anshitaaah_",
      },
      modal: {
        team: "Social Media",
        logo: "SocialMedia.webp",
        slogan: "Sharing info that open opportunity for you",
        desc: "Anshita Mishra is a third-year B.Tech student specializing in Cloud Computing, who thrives at the intersection of technology and communication. As a social media enthusiast with a knack for storytelling, Anshita brings a fresh perspective to online engagement, using her technical background to create content that not only informs but also captivates. With a deep understanding of cloud architectures and a passion for digital outreach, she's dedicated to building online communities that are as innovative as the technology she works with. Whether it's demystifying complex cloud concepts or sparking conversations on the latest tech trends, Anshita's goal is to make the world of cloud computing accessible and exciting for all.",
      },
      members: {
        mem1: "Parinita Singh",
        mem2: "Riya Dublish",
        mem3: "Asad Khan",
        mem4: "Sakshi Sharma",
        mem5: "",
        mem6: "",
        mem7: "",
        mem8: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "",
        det6: "",
        det7: "",
        det8: "",
      },
    },
    {
      id: 7,
      name: "Shreshth Sharma",
      position: "Design/Branding Head",
      img: "Shresth.webp",
      links: {
        link1: "https://www.linkedin.com/in/shreshthsharma2004/",
        link2: "https://github.com/shreshthUnderscore",
        link3: "",
      },
      modal: {
        team: "Designers",
        logo: "Designers.webp",
        slogan:
          "Good designs come with practice. Great designs come from the soul.",
        desc: "Shreshth Sharma is a passionate and dedicated individual with a strong proficiency in web development, particularly in designing websites that stand out both in functionality and aesthetics. His deep interest in design fuels his creativity, allowing him to craft unique and engaging digital experiences. Shreshth's strong problem-solving mindset, coupled with his ability to work effectively in a team, enables him to overcome challenges and deliver high-quality results. He is well-versed in a broad range of technical skills, including Python, MySQL, C++, and Adobe Photoshop, which he skillfully utilizes to bring his innovative ideas to life.In addition to his technical expertise, Shreshth is a disciplined and self-motivated student who consistently excels in his academic pursuits. He has a remarkable ability to balance his studies with his hobbies, actively engaging in coding and graphic design. His commitment to continuous learning and improvement is evident in the quality of his work, making him a valuable asset in any project or team he undertakes. Shreshth's combination of technical skills, creativity, and dedication positions him as a standout individual in both academic and professional settings.",
      },
      members: {
        mem1: "Ajeet Singh Rawat",
        mem2: "Sneha Gardiner",
        mem3: "Pranati Verma ",
        mem4: "Utkarshi Birla ",
        mem5: "Mohak Kansal",
        mem6: "",
        mem7: "",
        mem8: "",
        mem9: "",
      },
      details: {
        det1: "2nd year",
        det2: "2nd year",
        det3: "2nd year",
        det4: "3rd year",
        det5: "3rd year",
        det6: "",
        det7: "",
        det8: "",
        det9: "",
      },
    },
    {
      id: 8,
      name: "Archit Saxena",
      position: "P.R. Head",
      img: "Archit.webp",
      links: {
        link1:
          "https://www.linkedin.com/in/shobhitsgh?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        link2: "https://github.com/shobhitdevelops",
        link3:
          "https://www.instagram.com/_shobhitsingh?igsh=MXViamEwOTFiemU2MA==",
      },
      modal: {
        team: "P.R. And Outreach",
        logo: "PR.webp",
        slogan:
          "Since we cannot change the reality, let us change the eyes which see reality",
        desc: "Archit Saxena is our Public relations and outreach team lead is currently pursuing BTech in computer science and engineering. He is a fast and keen learner with a strong foundation in programming languages like C++. His knowledge extends to Object Oriented Programming, basic DSA and python. Also paving his way into Development. He is eager to continue expanding his skills and knowledge to contribute to the world of technology",
      },
      members: {
        mem1: "Aarush Rastogi",
        mem2: "Harshit Verma ",
        mem3: "Sanya Vohra",
        mem4: "Anurag Parashar",
        mem5: "",
        mem6: "",
      },
      details: {
        det1: "2nd year",
        det2: "3rd year",
        det3: "3rd year",
        det4: "3rd year",
        det5: "",
        det6: "",
      },
    },
  ],
};
